### ISSUE TITLE
Error Expresion

### ISSUE THREAD

**Issue by cowboyz4** [AgamlaRage/brackets-language-log#1]
Hi, view your main.js have a error expresión in 1 line (you have reuire) and I think it would be require, The code is still working but it is a syntax error

define(function (require, exports, module)

**Comment by AgamlaRage** [comment]
Hello ! Thx for posting this issue :)

This is a typing error that I will correct next commit !

However, I can't reproduce this error. I only can try on Windows right now.
Can you send me a screenshot, or the error explanation, and your OS version, please ?

**Comment by cowboyz4** [comment]
![error](https://cloud.githubusercontent.com/assets/12686738/20986617/a8c3066a-bcc9-11e6-9a1b-e1c61a31ce3a.png)
This is the image in Linux, I use windows 10 and linux,  the explanation of the error is the syntax is badly writte, I hope this answer helps you

**Comment by AgamlaRage** [comment]
The 'reuire' that a typing error as I said, but it's not making an error into the **Brackets webtools console** that you can access here.
![bll](https://cloud.githubusercontent.com/assets/15155827/20988390/d7641584-bcd0-11e6-9ab9-fd0da9a07fbc.png)

The other error I can see in your console (and mine now) is lint error, that not cause problem to the extension.

I made an update to the extension to fix the typing error and I also had a regexp to highlight the char into square brace (waiting to find a better solution to highlight dates)
